# frozen_string_literal: true

namespace :vial do
  desc 'Compile Vial sources into Rails fixtures'
  task :compile, [:only] => :environment do |_, args|
    only = args[:only] || ENV['ONLY']
    result = Vial.compile!(only: only)
    if result && result.status == :compiled
      puts "Vial: fixtures compiled to #{Vial.config.output_path}"
    end
  end

  desc 'Compile Vial sources without writing files (dry run)'
  task 'compile:dry_run', [:only] => :environment do |_, args|
    only = args[:only] || ENV['ONLY']
    result = Vial.compile!(dry_run: true, only: only)
    return unless result

    if result.status == :dry_run
      puts "Vial: dry run - would write #{result.files.size} fixture files to #{result.output_path}"
    end
  end

  desc 'Compile only selected vials (comma-separated, e.g. vial:compile:only[users,posts])'
  task 'compile:only', [:names] => :environment do |_, args|
    names = args[:names] || ENV['ONLY']
    if names.nil? || names.strip.empty?
      abort "Usage: bin/rails vial:compile:only[users,posts]"
    end

    result = Vial.compile!(only: names)
    if result && result.status == :compiled
      puts "Vial: fixtures compiled to #{Vial.config.output_path}"
    end
  end

  desc 'Remove fixture files generated by Vial that no longer have a matching vial definition'
  task clean: :environment do
    result = Vial.clean!
    return unless result

    if result.status == :cleaned
      if result.removed.empty?
        puts "Vial: no stale fixtures to remove"
      else
        puts "Vial: removed #{result.removed.size} stale fixture files"
      end
    end
  end

  desc 'Explain a derived ID (format: vial.label.variant[index])'
  task :explain_id, [:query] => :environment do |_, args|
    query = args[:query] || ENV['QUERY']
    if query.nil? || query.strip.empty?
      abort "Usage: bin/rails vial:explain_id['users.admin.eu[3]']"
    end

    begin
      vial_name, label, variants, index = Vial::ExplainId.parse(query)
    rescue ArgumentError => e
      abort e.message
    end
    Vial.load_sources!
    definition = Vial.registry[vial_name]
    abort "Unknown vial: #{vial_name}" unless definition

    info = definition.explain_id(label: label, variant_stack: variants, index: index)
    puts info[:normalized]
    puts "hash: #{info[:hash]}"
    puts "base: #{info[:base]}"
    puts "range: #{info[:range]}"
    puts "final: #{info[:final]}"
  end

  desc 'Count YAML fixture files across all configured fixture paths'
  task count_fixtures: :environment do
    # Need to load test environment to get fixture configuration
    require Rails.root.join('test/test_helper')
    
    # Rails 8+ uses fixture_paths as an attribute
    fixture_paths = ActiveSupport::TestCase.fixture_paths

    puts "Vial: Scanning fixture paths..."
    puts "Configured paths: #{fixture_paths.join(', ')}"
    puts

    total_count = 0
    fixture_counts = {}

    fixture_paths.each do |path|
      next unless File.directory?(path)

      yaml_files = Dir.glob(File.join(path, '**', '*.yml'))
      yaml_files += Dir.glob(File.join(path, '**', '*.yaml'))
      
      count = yaml_files.size
      total_count += count
      
      puts "#{path}: #{count} YAML files"
      
      # Group by subdirectory for better visibility
      yaml_files.each do |file|
        relative_path = Pathname.new(file).relative_path_from(Pathname.new(path))
        dir = relative_path.dirname.to_s
        fixture_counts[dir] ||= 0
        fixture_counts[dir] += 1
      end
    end

    puts
    puts "Fixture distribution by directory:"
    fixture_counts.sort.each do |dir, count|
      puts "  #{dir == '.' ? '(root)' : dir}: #{count} files"
    end

    puts
    puts "Total YAML fixtures found: #{total_count}"
  end
  
  desc 'Analyze fixtures and their model mappings'
  task analyze_fixtures: :environment do
    # Ensure test environment is loaded to get fixture configuration
    require Rails.root.join('test/test_helper')
    
    analyzer = Vial::FixtureAnalyzer.new
    analyzer.analyze
    
    puts "=== Vial Fixture Analysis ==="
    puts
    
    summary = analyzer.summary
    puts "Total fixtures found: #{summary[:total_fixtures]}"
    puts "Mapped to models: #{summary[:mapped_fixtures]}"
    puts "Unmapped fixtures: #{summary[:unmapped_fixtures]}"
    puts
    
    if analyzer.mapped_fixtures.any?
      puts "=== Mapped Fixtures ==="
      analyzer.mapped_fixtures.sort_by { |k, _| k }.each do |fixture_name, info|
        puts "#{fixture_name}:"
        puts "  Model: #{info.model_name}"
        puts "  Table: #{info.table_name}"
        puts "  Detection: #{info.detection_method}"
      end
      puts
    end
    
    if analyzer.unmapped_fixtures.any?
      puts "=== Unmapped Fixtures (Potential Issues) ==="
      analyzer.unmapped_fixtures.sort_by { |k, _| k }.each do |fixture_name, info|
        puts "#{fixture_name}:"
        puts "  File: #{info.file}"
        puts "  Status: No model found"
      end
      puts
    end
    
    if summary[:errors].any?
      puts "=== Errors ==="
      summary[:errors].each do |error|
        puts "File: #{error[:file]}"
        puts "Error: #{error[:error]}"
        puts
      end
    end
  end
  
  desc 'Validate fixtures - check for orphaned fixtures without models'
  task validate_fixtures: :environment do
    require Rails.root.join('test/test_helper')
    
    analyzer = Vial::FixtureAnalyzer.new
    analyzer.analyze
    
    unmapped = analyzer.unmapped_fixtures
    
    if unmapped.empty?
      puts "✅ All fixtures are properly mapped to models!"
      exit 0
    else
      puts "❌ Found #{unmapped.size} unmapped fixtures:"
      unmapped.sort_by { |k, _| k }.each do |fixture_name, info|
        puts "  - #{fixture_name}"
      end
      puts
      puts "These fixtures may:"
      puts "  1. Need a _fixture: model_class directive in the YAML"
      puts "  2. Need to be added to set_fixture_class in test_helper.rb"
      puts "  3. Be orphaned and should be removed"
      puts "  4. Have a model that doesn't follow Rails naming conventions"
      
      exit 1
    end
  end
  
  desc 'Analyze fixture IDs and check if they use proper ActiveRecord::FixtureSet.identify'
  task analyze_fixture_ids: :environment do
    require Rails.root.join('test/test_helper')
    
    standardizer = Vial::FixtureIdStandardizer.new
    standardizer.analyze
    
    summary = standardizer.summary
    
    puts "=== Vial Fixture ID Analysis ==="
    puts
    puts "Total fixtures analyzed: #{summary[:total_fixtures]}"
    puts "Fixtures needing ID updates: #{summary[:fixtures_needing_updates]}"
    puts "Total records to update: #{summary[:records_to_update]}"
    puts
    
    if summary[:primary_key_types].any?
      puts "Primary key types:"
      summary[:primary_key_types].sort.each do |type, count|
        puts "  #{type}: #{count} fixtures"
      end
      puts
    end
    
    if standardizer.updates_needed.any?
      puts "=== Fixtures Needing ID Standardization ==="
      standardizer.updates_needed.each do |update|
        puts
        puts "File: #{update.file}"
        puts "Model: #{update.model_class.name}"
        puts "Primary Key: #{update.primary_key} (#{update.primary_key_type})"
        puts "Changes needed:"
        update.changes.each do |change|
          puts "  #{change.label}:"
          puts "    Current: #{change.current_id.inspect}"
          puts "    Should be: #{change.new_id}"
        end
      end
    else
      puts "✅ All fixture IDs are properly standardized!"
    end
    
    if summary[:errors].any?
      puts
      puts "=== Errors ==="
      summary[:errors].each do |error|
        puts "File: #{error[:file]}"
        puts "Error: #{error[:error]}"
      end
    end
  end
  
  desc 'Standardize fixture IDs to use ActiveRecord::FixtureSet.identify'
  task standardize_fixture_ids: :environment do
    require Rails.root.join('test/test_helper')
    
    standardizer = Vial::FixtureIdStandardizer.new
    standardizer.analyze
    
    summary = standardizer.summary
    
    if summary[:records_to_update] == 0
      puts "✅ All fixture IDs are already standardized!"
      exit 0
    end
    
    puts "Will update #{summary[:records_to_update]} records across #{summary[:fixtures_needing_updates]} files."
    puts
    print "Continue? (y/N): "
    
    response = STDIN.gets.chomp.downcase
    
    if response == 'y'
      puts
      standardizer.standardize!(dry_run: false)
      puts
      puts "✅ Fixture IDs have been standardized!"
    else
      puts "Cancelled."
    end
  end
  
  desc 'Dry run of fixture ID standardization (preview changes without applying)'
  task 'standardize_fixture_ids:dry_run' => :environment do
    require Rails.root.join('test/test_helper')
    
    standardizer = Vial::FixtureIdStandardizer.new
    standardizer.analyze
    
    summary = standardizer.summary
    
    puts "=== Vial Fixture ID Standardization (DRY RUN) ==="
    puts
    puts "Would update #{summary[:records_to_update]} records across #{summary[:fixtures_needing_updates]} files."
    puts
    
    standardizer.standardize!(dry_run: true)
    
    if summary[:errors].any?
      puts
      puts "=== Errors ==="
      summary[:errors].each do |error|
        puts "File: #{error[:file]}"
        puts "Error: #{error[:error]}"
      end
    end
  end
end
